### ISSUE TITLE
Redesign genres desktop layout

### ISSUE THREAD

**Issue by Tokito69** [Tokito69/CoreProject-V3-UI#167]
@baseplate-admin 
We need to redesign genre desktop layout
It looks like not matching for the current UI design.

![Screenshot from 2023-05-21 08-07-35](https://github.com/sssuneeth/CoreProject-V3-UI/assets/114811070/6ab14f32-bbcb-4d92-9344-e761625b7057)
That many blue colors looks off?

Address your suggestions, here are mine:
- Redesign that anime cards a bit ( remove blue color from bottom and ... )
- Make anime cards scrollable

![Screenshot from 2023-05-19 17-14-53](https://github.com/sssuneeth/CoreProject-V3-UI/assets/114811070/f4b22a22-c502-46cd-a17a-fb033589627c)
Which design is good? I like second one, coz
- We dont need a popover, since we've enough details in that card itself
- And dont need to show buttons on hover
- And yea can make it scrollable

Here is the figma link with both designs: [kiss me](https://www.figma.com/file/0mwcNwR864qFl85vtpr7Bm/Core-Project-Mobile-design?type=design&node-id=4063-5045&t=KrPW1j59d2egVYy0-4)

**Comment by sssuneeth** [comment]
@baseplate-admin 
Now I'm thinking about redesigning whole genres section.
We've blank space on right side - we can add genres section there, because its not necessary ig.

I've a concept, will send demo :+1:
